### ISSUE TITLE
add brkraw 

### ISSUE THREAD

**Issue by timwahoo** [NeuroDesk/neurocontainers#601] opened 2024-02-22 18:16 UTC
The ‘BrkRaw’ is a python module designed to provide a comprehensive tool to access raw data acquired from Bruker Biospin preclinical MRI scanner. This module is also compatible with the zip compressed data to enable use of the archived data directly.
The module is comprised of four components, including graphical user interface (GUI), command-line tools, high-level and low-level python APIs.

    For the GUI, we focused on improving convenience for checking metadata and previewing the reconstructed image.
    For the command-line tool, we focused on providing tools for converting, organizing, archiving, and managing data. The command-line tool also provides easy-to-use function to convert large set of raw data into organized structure according to [BIDS](https://bids.neuroimaging.io/).
    For the high-level python API, we focused on enhancing the accessibility of reconstructed image data with preserved image orientation and metadata for the image analysis. It compatible users' convenient objects type ([nibabel](https://nipy.org/nibabel/) or [SimpleITK](https://simpleitk.readthedocs.io/en/master/gettingStarted.html#python-binary-files)) without the conversion step.
    For the low-level python API, we focused on providing a consistent method to access raw Bruker data including parameter and binary files with the python compatible datatype while keeping the sake of simplicity.

**Comment by stebo85** [comment] 2024-02-22 20:19
@Vbitz - could you try building this container using your new system?

**Comment by stebo85** [comment] 2024-02-27 06:55
Dear @timwahoo - brkraw is added now :) You need to run the update function in the application menu to see the entry in the application menu.

Let us know if it works well for you!

**Comment by timwahoo** [comment] 2024-02-27 14:21
That's amazing, Thank you!

**Comment by timwahoo** [comment] 2024-02-27 16:48
Hi @stebo85,

I tried to use brkraw on neurodesktop and was able to use it through singularity exec. Is there a way to add the library's CLI as well? 

Thank you!

**Comment by stebo85** [comment] 2024-02-28 06:51
Dear @timwahoo,

You have have two options to access the CLI:
1) Click the update button in the Application menu and start the application from the Data Organisation tab -> brkraw -> brkraw 0.3.11. This will open the terminal with the CLI:
<img width="1608" alt="image" src="https://github.com/NeuroDesk/neurocontainers/assets/4021595/f11b0fa8-3da0-4984-a498-59f88b620f92">

Alternatively, you can use the module system (there was a little bug there before, but this is fixed now):
<img width="891" alt="image" src="https://github.com/NeuroDesk/neurocontainers/assets/4021595/4d667464-f915-4505-aa10-74661ed2b75a">


Let us know if this works well for you :)

**Comment by timwahoo** [comment] 2024-02-28 15:27
Hi [stebo85](https://github.com/stebo85),

Thank you for the update! Yes I was able to get it to work, but I ran into a problem with the brkraw when testing it with my datasets. I'm not sure why this error occurred. 

I am a developer for this software, so I'd be happy to get this software working on neurodesktop. Is there anyway for me to debug the singularity container?

![image](https://github.com/NeuroDesk/neurocontainers/assets/139504215/f95755e5-e946-4f6b-b7b9-66b94134236e)

**Comment by stebo85** [comment] 2024-02-28 20:07
What do you mean with debug? Would it help to be able to install packages?

If yes you can make the singularity container writable: singularity shell --writable

**Comment by timwahoo** [comment] 2024-02-28 20:31
I think the issue is the reading/opening the Bruker files through the singularity container. However, I'm not sure if that is the issue without confirming it because it works fine when installed on a local host machine.

I do not think any other packages need to be installed.

**Comment by stebo85** [comment] 2024-02-28 21:06
Ahh, when running through singularity did you make sure you can read the file in the first place? Did you bind mount the directory where the data is located?

**Comment by stebo85** [comment] 2024-03-19 05:55
Dear @timwahoo - are there any updates on this problem? Can you give us test dataset so we can also try to figure out why it's not working on our end?

**Comment by timwahoo** [comment] 2024-03-20 03:09
Hi @stebo85, 

Yes, I have tried it with different datasets and it only fails on datasets obtained from Bruker ParaVision 360. The problem is definitely in the brkraw side of things. 

Here is a link to my datasets https://drive.google.com/drive/folders/1_3xzqR8CJD4VC1DIhy7lT_zyFYe2Pfyy?usp=sharing

**Comment by stebo85** [comment] 2024-03-20 03:41
Dear @timwahoo 

Ok, that's great to know! So should we update to v0.3.11 and the problem is solved?

**Comment by Vbitz** [comment] 2024-03-20 03:56
Should be fixed with #625. A new container should be built soon.

`brkraw` changed their pip package name in a recent version. I've tested locally and it returns v0.3.11

**Comment by stebo85** [comment] 2024-03-20 03:57
thank you!

**Comment by stebo85** [comment] 2024-03-20 06:58
Dear @timwahoo,

This is fixed now: 
<img width="533" alt="image" src="https://github.com/NeuroDesk/neurocontainers/assets/4021595/43c9df71-d32e-4afa-a5ec-88b65584bf0a">


can you test on your side?

**Comment by timwahoo** [comment] 2024-03-20 16:45
It works great, thank you for taking the time and effort!

**Comment by stebo85** [comment] 2024-03-20 22:56
great to hear and thank you for confirming!

**Closed by stebo85** 2024-03-20 22:56 UTC
